---
title: "Plotly examples"
output: 
  html_document:
    toc: true
    toc_float: true

---

# Examples of plotly

We're gonna look at NYC Airbnb data

```{r}
library(tidyverse)
library(plotly)
```

# Loading data

```{r}
nyc_airbnb = 
  read_csv("nyc_airbnb.csv")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>% 
  select(neighbourhood_group, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    neighbourhood_group == "Manhattan",
    price %in% 100:500,
    room_type == "Entire home/apt"
  ) %>% 
  drop_na(rating)
  
```

# Plotly plots

## scatterplots

```{r}
nyc_airbnb %>% 
  mutate(text_label = str_c("Price: $", price, " Rating: ", rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label, alpha = .5,
    type = "scatter", mode = "markers")
```

## boxplot

```{r}
nyc_airbnb %>% 
  # reorder the neighbourhood variable based on price
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, x = ~neighbourhood, color = ~neighbourhood,
          type = "box", colors = "viridis")
```

## barplot

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>% 
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood,
          type = "bar", colors = "viridis")
```

# ggplotly 

```{r}
ggp_scatter = 
  nyc_airbnb %>% 
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point()

ggplotly(ggp_scatter)
```








